name: Release version

on:
  push:
    branches: ["main"]
jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Checkout
      - uses: actions/checkout@v3

#       - name: Git configuration
#         run: |
#           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --global user.name "GitHub Actions"

#       - name: Setup Node.js
#         uses: actions/setup-node@v3

#       - name: Install dependencies
#         run: npm install

#       - name: Generate version
#       - run: npm run release
